#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# 커밋 메시지 패턴 정의 (예: "type: subject")
pattern="^(feat|fix|docs|style|refactor|test|chore): .{1,50}$"

if ! [[ "$commit_msg" =~ $pattern ]]; then
    echo "오류: 커밋 메시지가 지정된 규칙을 따르지 않습니다."
    echo "커밋 메시지는 다음 형식을 따라야 합니다: type: subject"
    echo "허용되는 타입: feat, fix, docs, style, refactor, test, chore, init"
    echo "제목(subject)은 50자를 넘지 않아야 합니다."
    exit 1
fi

