crawler:
  api_client: ZhfHyfP_euzCwdM95Pad
  api_secret: 6vcvEw0Bwg
  crawler_display: 10
  crawler_sort: date
  dart_secret: d3b83a3274a6c9e5ec82921e8fa953353e5f3bfc

elastic_search:
  host: https://j11a606.p.ssafy.io:9200
  id: elastic
  password: ssafya606