crawler:
  api_client: ZhfHyfP_euzCwdM95Pad
  api_secret: 6vcvEw0Bwg
  crawler_display: 10
  crawler_sort: date
  dart_secret: 5819b814ebeb6d4653b8f662554255be23d501f2

elastic_search:
  host: https://j11a606.p.ssafy.io:9200
  id: elastic
  password: ssafya606