version: '3'
services:
  api_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DART_SERVICE_URL=${DART_SERVICE_URL:-http://host.docker.internal:8002}
      - NEWS_SERVICE_URL=${NEWS_SERVICE_URL:-http://host.docker.internal:8001}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: api-app-network